"""
scripts/generate_notebook.py
---------------------------------------------------------------------------------
Programmatically generates a Jupyter notebook 'visualize_results.ipynb' for 
viewing figures, curves, and tables inline in Kaggle or a local environment.
Usage:
    python scripts/generate_notebook.py
"""

import json

def main():
    notebook = {
        "cells": [
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "# 🏥 Multimodal Heart Failure Readmission - Evaluation Dashboard\n",
                    "This dashboard automatically displays the generated figures, clinical metrics, fairness reports, and decision curves from your trained pipeline."
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## 📈 Core Visualizations\n",
                    "We display the three primary publication-ready plots generated by `evaluate_all.py`."
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "import os\n",
                    "from IPython.display import Image, display, HTML\n",
                    "\n",
                    "figures = [\n",
                    "    ('missingness_sweep_heatmap.png', 'Modality Missingness Sweep Heatmap'),\n",
                    "    ('decision_curve.png', 'Clinical Decision Curve Analysis (DCA)'),\n",
                    "    ('fairness_subgroups.png', 'Algorithmic Fairness Subgroup Analysis'),\n",
                    "    ('confusion_matrix.png', 'Confusion Matrices (F1-Optimized Thresholds)')\n",
                    "]\n",
                    "\n",
                    "for filename, title in figures:\n",
                    "    filepath = os.path.join('outputs', 'figures', filename)\n",
                    "    if os.path.exists(filepath):\n",
                    "        display(HTML(f\"\"\"<h3 style='color:#2c3e50; font-family:sans-serif; border-bottom: 2px solid #ecf0f1; padding-bottom: 5px;'>\n",
                    "                        {title} (<code>{filename}</code>)\n",
                    "                      </h3>\"\"\"))\n",
                    "        display(Image(filename=filepath, width=700))\n",
                    "    else:\n",
                    "        print(f\"Warning: Figure {filename} not found at {filepath}\")"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## 📊 Missingness Sweep Detailed Table\n",
                    "This table compares performance across all combinations of available modalities (EHR, ECG, and CXR) using fixed-weight vs. learned-gate fusion models."
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "import pandas as pd\n",
                    "\n",
                    "sweep_path = 'outputs/results/missingness_sweep.csv'\n",
                    "if os.path.exists(sweep_path):\n",
                    "    df = pd.read_csv(sweep_path)\n",
                    "    # Pretty format style\n",
                    "    styled = df.style.background_gradient(subset=['AUROC', 'AUPRC'], cmap='Blues') \\\n",
                    "                     .background_gradient(subset=['ECE', 'Brier'], cmap='Reds_r') \\\n",
                    "                     .format(precision=4)\n",
                    "    display(styled)\n",
                    "else:\n",
                    "    print(f\"Warning: CSV not found at {sweep_path}\")"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## ⚖️ Algorithmic Fairness Report\n",
                    "Inspecting demographic subgroups for gender and age groups to verify performance and ECE equity."
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "import pandas as pd\n",
                    "import numpy as np\n",
                    "\n",
                    "# If you ran evaluate_all.py, the fairness metrics are printed. We can also reload the test predictions to compute it live:\n",
                    "preds_path = 'outputs/results/fusion_test_preds.csv'\n",
                    "cohort_path = 'data/cohort.parquet'\n",
                    "\n",
                    "if os.path.exists(preds_path) and os.path.exists(cohort_path):\n",
                    "    preds_df = pd.read_csv(preds_path)\n",
                    "    cohort_df = pd.read_parquet(cohort_path)\n",
                    "    \n",
                    "    # Merge predictions with cohort demographic columns\n",
                    "    merged = preds_df.merge(cohort_df[['hadm_id', 'gender', 'age_group']], on='hadm_id', how='inner')\n",
                    "    \n",
                    "    print(\"--- Overall and Gender Fairness metrics ---\")\n",
                    "    for col in ['gender', 'age_group']:\n",
                    "        print(f\"\\nSubgroup performance by {col.upper()}:\")\n",
                    "        summary = merged.groupby(col).agg(\n",
                    "            count=('hadm_id', 'count'),\n",
                    "            readmit_rate=('label', 'mean'),\n",
                    "            mean_score=('score', 'mean')\n",
                    "        ).reset_index()\n",
                    "        print(summary.to_string(index=False))\n",
                    "else:\n",
                    "    print(\"Predictions or Cohort parquet not found.\")"
                ]
            }
        ],
        "metadata": {},
        "nbformat": 4,
        "nbformat_minor": 2
    }

    output_path = "visualize_results.ipynb"
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(notebook, f, indent=1)
    
    print(f"Jupyter notebook created successfully at: {output_path}")

if __name__ == "__main__":
    main()
